---
kind: Delpoyment
apiVersion: apps/v1
metadata:
  name: web-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      name: web-pod
      labels:
        app: webui
    spec:
      containers:
      - name: web-container
        image: nginx:1.14
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: web-depl-svc
spec:
  type: ClusterIP
  clusterip: None
  selector:
    app: webui
  port
