---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-deploy
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password



---
kind: Service
apiVersion: v1
metadata:
  name: mongodb-svc
  labels:
    app: mongodb
spec:
  type: ClusterIP
  # clusterIP: 10.100.10.10
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
