---
kind: Pod
apiVersion: v1
metadata:
  name: label-pod
  labels:
    name: mainui
    rel: stable
spec:
  containers:
  - name: label-container
    image: nginx
    ports:
    - containerPort: 80
    