---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-liveness-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      periodSeconds: 30
      timeoutSeconds: 3
     # successThreshold: 1
     # failureThreshold: 3

