---
kind: Pod
apiVersion: v1
metadata:
  name: genid-stone
spec:
  containers:
  - name: fakeid
    image: kokoball8686/genid
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: test-config
          key: INTERVAL
    volumeMounts:
    - name: html
      mountPath: /webdata

  - name: web-server
    image: nginx:1.14
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html


  volumes:
  - name: html
    emptyDir: {}
