apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
spec:
  # type: ClusterIP
  # clusterIP: 10.100.10.10
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80