---
kind: Pod
apiVersion: v1
metadata:
  name: wrong-pod-nodeselector
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  nodeSelector:
    gpu: "true"
    disk: ssd
    mem: high
    
