apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: ten
          topologyKey: kubernetes.io/hostname
  containers:
  - name: with-pod-affinity
    image: mongo
    ports:
    - containerPort: 27017
